"""Aalto-calibrated population prior for keyboard behavioural features.

Uses pre-computed population statistics derived from the Aalto 136 Million
Keystrokes dataset (Dhakal, Feit, Kristensson, Oulasvirta; CHI 2018,
168 960 participants typing free-text sentences).

This prior serves one purpose: telling the system how much *humans in general*
differ on each keyboard feature.  It does NOT identify users, assign them to
clusters, or make any personalisation decisions.

    Aalto = "how much do people vary?"
    User  = "what does THIS person do?"

The prior covers keyboard features only.  Aalto captured typing; it did not
capture pointer movements or form-interaction patterns.  The pointer and
interaction modalities fall back to the existing relative prior, with no
fabricated numbers.

Usage::

    from app.behavioral.fingerprint.aalto_prior import load_aalto_prior
    prior = load_aalto_prior()
    # prior is a PopulationPrior with empirical scales from 168K+ users

Integration with the existing PopulationPrior is deliberate: the same
interface, the same ``scale_for()`` method, the same downstream code.  The
Aalto prior enhances the population prior rather than replacing it — if the
database also has live volunteer samples, both sources are available.
"""

from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass, field
from pathlib import Path

from app.behavioral.features.registry import Modality, SPECS
from app.behavioral.fingerprint.population import PopulationPrior

log = logging.getLogger("bioprint.aalto_prior")

# Shipped artifact. Generated by precompute_aalto_prior.py.
#
# ACTIVE: the real prior, computed from the full Aalto corpus (168,593
# participants, 2,528,895 sessions, 123,107,831 keystrokes). It replaced the
# synthetic bootstrap after a controlled A/B in which the ONLY variable was
# this path. Same generated typists, same seeds, same code
# (evaluation/enrollment_size_ablation.py, two seeds, 1200 genuine and 1200
# impostor attempts per condition):
#
#   2 captures, same threshold   false acceptance  29.8% -> 10.1%
#                                false rejection    0.7% ->  3.2%
#   equal-error rate             1 cap 10.8%->8.5%   2 cap 7.9%->6.4%   8 cap 2.8%->2.2%
#   ROC-AUC                      improved at every enrollment size
#   thresholds calibrated on 60 users, reported on 60 disjoint held-out users:
#                                2-capture FRR 15.8% -> 11.3% at equal FAR
#
# A freshly enrolled account admitting three in ten strangers who hold the
# password was the weakest thing in the product; this cuts that threefold at
# the same threshold, with no security parameter changed to achieve it.
#
# The cost is honest and stated: cold-start false rejection rises from ~0.7%
# to ~3.2%, roughly one retry in thirty, during a state that ends when the
# profile matures.
#
# Generated typists. NOT real-human calibration — no such study was run.
#
# The synthetic bootstrap is preserved at aalto_prior_synthetic_bootstrap.json
# and aalto_prior.json for comparison and rollback. Rollback is one env var:
# BIOPRINT_AALTO_PRIOR_PATH=data/aalto_prior.json
_DEFAULT_PRIOR_PATH = (
    Path(__file__).resolve().parent.parent.parent.parent
    / "data" / "aalto_prior_real.json"
)


def _prior_path() -> Path:
    """Which prior artifact to load.

    The default is the shipped one and does not change. The environment
    override exists so an ablation can run the whole system against an
    alternative prior without copying a file over the production artifact —
    a swap that would leave the wrong prior active if the run crashed halfway.

    Read per call rather than captured at import, so a test can set it after
    this module is already loaded.
    """
    override = os.environ.get("BIOPRINT_AALTO_PRIOR_PATH")
    return Path(override) if override else _DEFAULT_PRIOR_PATH

# Features the Aalto dataset cannot populate (no pointer or interaction data).
_AALTO_UNSUPPORTED_MODALITIES = frozenset({Modality.POINTER, Modality.INTERACTION})


@dataclass(frozen=True)
class AaltoFeatureStat:
    """Population statistics for one keyboard feature, from Aalto data."""

    name: str
    population_median: float
    population_mad: float
    population_scale: float  # MAD * 1.4826, consistent estimator of sigma
    p10: float
    p25: float
    p75: float
    p90: float
    n_users: int  # how many Aalto users contributed to this feature
    source_note: str = ""


@dataclass(frozen=True)
class UnobservedFeature:
    """A feature the source dataset structurally cannot measure.

    Kept separate from AaltoFeatureStat with no numeric fields at all, because
    the distinction this class exists to protect is:

        unobserved      we have no idea how much people vary on this
        scale == 0.0    people do not vary on this at all

    Those demand opposite behaviour. Unobserved must fall back to the relative
    prior; zero variability would mean any deviation is infinitely significant.
    Giving this type no median and no scale makes the second reading
    unavailable rather than merely discouraged.
    """

    name: str
    reason: str = ""


@dataclass(frozen=True)
class AaltoPrior:
    """Complete Aalto-derived population prior for keyboard features."""

    features: dict[str, AaltoFeatureStat] = field(default_factory=dict)
    unobserved: dict[str, UnobservedFeature] = field(default_factory=dict)
    total_users: int = 0
    source: str = ""
    note: str = ""
    dataset_type: str = "unknown"

    @property
    def is_loaded(self) -> bool:
        return bool(self.features)

    @property
    def keyboard_feature_count(self) -> int:
        """Observed features only. An unobserved feature is not a statistic."""
        return len(self.features)

    def is_unobserved(self, name: str) -> bool:
        return name in self.unobserved

    def to_population_prior(self) -> PopulationPrior:
        """Convert to the standard PopulationPrior used throughout the system.

        The PopulationPrior stores per-feature robust scales and a sample count.
        The sample count drives the shrinkage calculation in ``scale_for()``:
        with 168K users the empirical estimate is trusted almost completely.

        Unobserved features contribute no entry, so `PopulationPrior.scale_for`
        falls through to the relative prior for them — the same path a pointer
        feature takes. That is the intended behaviour: no empirical estimate
        means use the fallback, never means the spread is zero.
        """
        scales = {
            name: stat.population_scale
            for name, stat in self.features.items()
            if stat.population_scale > 0.0
        }
        return PopulationPrior(scales=scales, sample_count=self.total_users)

    def describe(self) -> dict[str, object]:
        return {
            "source": self.source,
            "dataset_type": self.dataset_type,
            "total_users": self.total_users,
            "keyboard_features": self.keyboard_feature_count,
            "unobserved_features": sorted(self.unobserved),
            "pointer_features": 0,
            "interaction_features": 0,
            "note": self.note,
        }


def load_aalto_prior(path: Path | None = None) -> AaltoPrior:
    """Load the pre-computed Aalto population prior from disk.

    Returns an empty AaltoPrior (with ``is_loaded == False``) if the artifact
    is missing, so callers can always try and fall back gracefully.
    """
    artifact = path or _prior_path()
    if not artifact.exists():
        log.info("Aalto prior not found at %s — using database population only", artifact)
        return AaltoPrior()

    try:
        with open(artifact, "r", encoding="utf-8") as f:
            payload = json.load(f)
    except (json.JSONDecodeError, OSError) as exc:
        log.warning("Failed to load Aalto prior from %s: %s", artifact, exc)
        return AaltoPrior()

    return _parse_prior(payload)


def _parse_prior(payload: dict) -> AaltoPrior:
    meta = payload.get("meta", {})
    features_raw = payload.get("features", {})

    features: dict[str, AaltoFeatureStat] = {}
    unobserved: dict[str, UnobservedFeature] = {}
    for name, data in features_raw.items():
        # Only accept features that exist in our registry and are keyboard.
        spec = SPECS.get(name)
        if spec is None:
            log.debug("Aalto prior contains unknown feature %r — skipping", name)
            continue
        if spec.modality in _AALTO_UNSUPPORTED_MODALITIES:
            log.warning(
                "Aalto prior claims to contain %s feature %r — this is impossible "
                "(Aalto has no %s data). Skipping.",
                spec.modality.value, name, spec.modality.value,
            )
            continue

        # An explicitly unobserved feature never becomes a statistic. Without
        # this branch the float() defaults below would turn it into a
        # zero-median, zero-scale entry that reads exactly like a real
        # measurement of a feature nobody varies on.
        if str(data.get("status", "observed")).lower() == "unobserved":
            unobserved[name] = UnobservedFeature(
                name=name, reason=str(data.get("reason", ""))
            )
            continue

        features[name] = AaltoFeatureStat(
            name=name,
            population_median=float(data.get("population_median", 0.0)),
            population_mad=float(data.get("population_mad", 0.0)),
            population_scale=float(data.get("population_scale", 0.0)),
            p10=float(data.get("p10", 0.0)),
            p25=float(data.get("p25", 0.0)),
            p75=float(data.get("p75", 0.0)),
            p90=float(data.get("p90", 0.0)),
            n_users=int(data.get("n_users", 0)),
            source_note=str(data.get("source_note", "")),
        )

    total_users = int(meta.get("n_users", 0))
    source = str(meta.get("source", "unknown"))
    note = str(meta.get("note", ""))

    prior = AaltoPrior(
        features=features,
        unobserved=unobserved,
        total_users=total_users,
        source=source,
        note=note,
        dataset_type=str(meta.get("dataset_type", "unknown")),
    )

    log.info(
        "Loaded Aalto prior: %d keyboard features (%d unobserved), %d users, source=%s",
        prior.keyboard_feature_count,
        len(prior.unobserved),
        prior.total_users,
        prior.source,
    )
    return prior


def aalto_population_prior(path: Path | None = None) -> PopulationPrior | None:
    """Convenience: load the Aalto artifact and return a PopulationPrior.

    Returns None if the artifact is not available, so callers can fall back to
    the database-backed prior without special-casing.
    """
    prior = load_aalto_prior(path)
    if not prior.is_loaded:
        return None
    return prior.to_population_prior()
