"""Reason codes returned with every authentication decision.

Two audiences, deliberately separated:

* `code` is machine-readable and stable — the evaluation
  harness and the tests key off it.
* `explain()` is what a blocked user sees. It says which *category* of signal
  disagreed without disclosing feature names, thresholds or score margins,
  because an attacker who can read "typing rhythm was 0.3 too slow" off the
  error page gets a gradient to climb.
"""

from __future__ import annotations

from enum import StrEnum


class ReasonCode(StrEnum):
    # --- allow ---
    BEHAVIOR_MATCH = "BEHAVIOR_MATCH"

    # --- credential layer (never mixed into the behavioural scores) ---
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ACCOUNT_NOT_ENROLLED = "ACCOUNT_NOT_ENROLLED"

    # --- integrity / replay ---
    CHALLENGE_UNKNOWN = "CHALLENGE_UNKNOWN"
    CHALLENGE_EXPIRED = "CHALLENGE_EXPIRED"
    CHALLENGE_REUSED = "CHALLENGE_REUSED"
    CHALLENGE_WRONG_USER = "CHALLENGE_WRONG_USER"
    PHRASE_MISMATCH = "PHRASE_MISMATCH"
    MALFORMED_EVENT_STREAM = "MALFORMED_EVENT_STREAM"
    TIMESTAMP_INCONSISTENT = "TIMESTAMP_INCONSISTENT"

    # --- automation ---
    AUTOMATION_TIMING = "AUTOMATION_TIMING"
    SYNTHETIC_EVENT_ORDER = "SYNTHETIC_EVENT_ORDER"
    LOW_TIMING_VARIABILITY = "LOW_TIMING_VARIABILITY"
    DWELL_DEGENERACY = "DWELL_DEGENERACY"
    POINTER_ANOMALY = "POINTER_ANOMALY"
    IMPOSSIBLE_INTERACTION_SPEED = "IMPOSSIBLE_INTERACTION_SPEED"
    UNTRUSTED_EVENTS = "UNTRUSTED_EVENTS"
    AUTOMATION_DETECTED = "AUTOMATION_DETECTED"

    # --- identity ---
    BEHAVIORAL_MISMATCH = "BEHAVIORAL_MISMATCH"
    KEYSTROKE_MISMATCH = "KEYSTROKE_MISMATCH"
    POINTER_MISMATCH = "POINTER_MISMATCH"
    INTERACTION_MISMATCH = "INTERACTION_MISMATCH"

    # --- coverage ---
    INSUFFICIENT_SIGNAL = "INSUFFICIENT_SIGNAL"


# User-facing text. Vague on purpose for anything an attacker could tune against.
_EXPLANATIONS: dict[ReasonCode, str] = {
    ReasonCode.BEHAVIOR_MATCH: "Interaction matched the enrolled behavioural profile.",
    ReasonCode.INVALID_CREDENTIALS: "Username or password is incorrect.",
    ReasonCode.ACCOUNT_NOT_ENROLLED: "This account has no behavioural profile yet. Complete enrollment first.",
    ReasonCode.CHALLENGE_UNKNOWN: "This login challenge is not recognised.",
    ReasonCode.CHALLENGE_EXPIRED: "This login challenge expired. Start a new attempt.",
    ReasonCode.CHALLENGE_REUSED: "This login challenge has already been used.",
    ReasonCode.CHALLENGE_WRONG_USER: "This login challenge was issued for a different account.",
    ReasonCode.PHRASE_MISMATCH: "The verification phrase was not entered correctly.",
    ReasonCode.MALFORMED_EVENT_STREAM: "The interaction data was incomplete or inconsistent.",
    ReasonCode.TIMESTAMP_INCONSISTENT: "The interaction timing was inconsistent with this attempt.",
    ReasonCode.AUTOMATION_TIMING: "Interaction timing showed machine-generated regularity.",
    ReasonCode.SYNTHETIC_EVENT_ORDER: "Input events did not follow a physically plausible order.",
    ReasonCode.LOW_TIMING_VARIABILITY: "Timing lacked the natural variation of human input.",
    ReasonCode.DWELL_DEGENERACY: "Key press durations were unnaturally uniform.",
    ReasonCode.POINTER_ANOMALY: "Pointer movement did not resemble human motor control.",
    ReasonCode.IMPOSSIBLE_INTERACTION_SPEED: "The form was completed faster than is humanly possible.",
    ReasonCode.UNTRUSTED_EVENTS: "Input events were not generated by genuine user interaction.",
    ReasonCode.AUTOMATION_DETECTED: "This attempt appears to be automated rather than human.",
    ReasonCode.BEHAVIORAL_MISMATCH: "Interaction behaviour did not match the enrolled profile.",
    ReasonCode.KEYSTROKE_MISMATCH: "Typing rhythm differed from the enrolled profile.",
    ReasonCode.POINTER_MISMATCH: "Pointer movement differed from the enrolled profile.",
    ReasonCode.INTERACTION_MISMATCH: "Form interaction pattern differed from the enrolled profile.",
    ReasonCode.INSUFFICIENT_SIGNAL: "Not enough interaction was captured to make a decision. Please try again.",
}


def explain(code: ReasonCode) -> str:
    return _EXPLANATIONS.get(code, "Authentication could not be completed.")


# Short labels. Categories only — no thresholds or feature names.
_HEADLINES: dict[ReasonCode, str] = {
    ReasonCode.BEHAVIOR_MATCH: "ACCESS GRANTED",
    ReasonCode.INVALID_CREDENTIALS: "ACCESS BLOCKED",
    ReasonCode.ACCOUNT_NOT_ENROLLED: "ACCESS BLOCKED",
    ReasonCode.AUTOMATION_DETECTED: "AUTOMATION DETECTED",
    ReasonCode.BEHAVIORAL_MISMATCH: "BEHAVIORAL MISMATCH",
    ReasonCode.KEYSTROKE_MISMATCH: "BEHAVIORAL MISMATCH",
    ReasonCode.POINTER_MISMATCH: "BEHAVIORAL MISMATCH",
    ReasonCode.INTERACTION_MISMATCH: "BEHAVIORAL MISMATCH",
    ReasonCode.INSUFFICIENT_SIGNAL: "INSUFFICIENT SIGNAL",
    ReasonCode.CHALLENGE_EXPIRED: "CHALLENGE EXPIRED",
    ReasonCode.CHALLENGE_REUSED: "REPLAY / CHALLENGE FAILURE",
    ReasonCode.CHALLENGE_UNKNOWN: "REPLAY / CHALLENGE FAILURE",
    ReasonCode.CHALLENGE_WRONG_USER: "REPLAY / CHALLENGE FAILURE",
    ReasonCode.PHRASE_MISMATCH: "REPLAY / CHALLENGE FAILURE",
    ReasonCode.MALFORMED_EVENT_STREAM: "REPLAY / CHALLENGE FAILURE",
    ReasonCode.TIMESTAMP_INCONSISTENT: "REPLAY / CHALLENGE FAILURE",
}


def headline(code: ReasonCode | str) -> str:
    if not isinstance(code, ReasonCode):
        try:
            code = ReasonCode(code)
        except ValueError:
            return "ACCESS BLOCKED"
    return _HEADLINES.get(code, "ACCESS BLOCKED")


def integrity_status(reason: ReasonCode | str, integrity_score: float | None) -> str:
    if not isinstance(reason, ReasonCode):
        try:
            reason = ReasonCode(reason)
        except ValueError:
            return "FAIL"
    if reason in {
        ReasonCode.CHALLENGE_EXPIRED,
        ReasonCode.CHALLENGE_REUSED,
        ReasonCode.CHALLENGE_UNKNOWN,
        ReasonCode.CHALLENGE_WRONG_USER,
        ReasonCode.PHRASE_MISMATCH,
        ReasonCode.MALFORMED_EVENT_STREAM,
        ReasonCode.TIMESTAMP_INCONSISTENT,
    }:
        return "FAIL"
    if integrity_score is not None and integrity_score >= 0.5:
        return "FAIL"
    return "PASS"


# Coarse severity band shown next to each contributing signal.
def band(normalised: float) -> str:
    """Map a 0..1 deviation onto LOW / MEDIUM / HIGH for display."""
    if normalised < 0.34:
        return "LOW"
    if normalised < 0.67:
        return "MEDIUM"
    return "HIGH"
